[2025-04-14T15:21:17.614+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-14T15:21:17.630+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: batdongsan_scraping.save_links manual__2025-04-14T15:21:16.182904+00:00 [queued]>
[2025-04-14T15:21:17.638+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: batdongsan_scraping.save_links manual__2025-04-14T15:21:16.182904+00:00 [queued]>
[2025-04-14T15:21:17.638+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-14T15:21:17.650+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): save_links> on 2025-04-14 15:21:16.182904+00:00
[2025-04-14T15:21:17.662+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'batdongsan_scraping', 'save_links', 'manual__2025-04-14T15:21:16.182904+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/batdongsan_scraping_dag.py', '--cfg-path', '/tmp/tmpn0ty52bf']
[2025-04-14T15:21:17.665+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask save_links
[2025-04-14T15:21:17.665+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=211) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-14T15:21:17.666+0000] {standard_task_runner.py:72} INFO - Started process 215 to run task
[2025-04-14T15:21:17.706+0000] {task_command.py:467} INFO - Running <TaskInstance: batdongsan_scraping.save_links manual__2025-04-14T15:21:16.182904+00:00 [running]> on host 932270897c9d
[2025-04-14T15:21:17.763+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='batdongsan_scraping' AIRFLOW_CTX_TASK_ID='save_links' AIRFLOW_CTX_EXECUTION_DATE='2025-04-14T15:21:16.182904+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-14T15:21:16.182904+00:00'
[2025-04-14T15:21:17.767+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-14T15:21:17.834+0000] {SaveLinkBatdongsan.py:104} INFO - Loaded 60334 existing links
[2025-04-14T15:21:17.836+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:20.178+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:20.257+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 1: Message: Service /home/***/.local/share/undetected_chromedriver/undetected_chromedriver unexpectedly exited. Status code was: -5

[2025-04-14T15:21:20.264+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:21.732+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:21.767+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 2: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:21.769+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:23.294+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:23.317+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 3: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:23.318+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:28.554+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:28.590+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 4: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:28.591+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:29.770+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:29.785+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 5: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:29.786+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:31.117+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:31.162+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 6: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:31.164+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:32.400+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:32.420+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 7: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:32.420+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:33.679+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:33.709+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 8: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:33.713+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:34.833+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:34.850+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 9: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:34.851+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:36.047+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:36.063+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 10: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:36.289+0000] {SaveLinkBatdongsan.py:111} INFO - Saved 60334 links to /opt/***/data/batdongsan_links.txt
[2025-04-14T15:21:36.289+0000] {SaveLinkBatdongsan.py:160} INFO - Progress saved at page 10
[2025-04-14T15:21:36.290+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:37.542+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:37.582+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 11: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:37.583+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:38.975+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:38.997+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 12: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:38.998+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:40.114+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:40.133+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 13: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:40.134+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:41.292+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:41.316+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 14: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:41.317+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:42.600+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:42.616+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 15: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:42.617+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:43.760+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:43.780+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 16: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:43.781+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:47.414+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:47.438+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 17: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:47.439+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:48.614+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:48.638+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 18: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:48.639+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:49.921+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:49.945+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 19: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:49.946+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:51.142+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:51.161+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 20: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:51.480+0000] {SaveLinkBatdongsan.py:111} INFO - Saved 60334 links to /opt/***/data/batdongsan_links.txt
[2025-04-14T15:21:51.480+0000] {SaveLinkBatdongsan.py:160} INFO - Progress saved at page 20
[2025-04-14T15:21:51.480+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:52.787+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:52.810+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 21: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:52.810+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:54.081+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:54.098+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 22: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:54.099+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:55.527+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:55.560+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 23: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:55.561+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:56.821+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:56.846+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 24: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:56.847+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:58.778+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:58.810+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 25: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:58.812+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:00.090+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:00.114+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 26: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:00.114+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:01.479+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:01.506+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 27: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:01.507+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:02.718+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:02.735+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 28: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:02.738+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:04.054+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:04.071+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 29: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:04.072+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:05.299+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:05.338+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 30: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:05.790+0000] {SaveLinkBatdongsan.py:111} INFO - Saved 60334 links to /opt/***/data/batdongsan_links.txt
[2025-04-14T15:22:05.792+0000] {SaveLinkBatdongsan.py:160} INFO - Progress saved at page 30
[2025-04-14T15:22:05.792+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:07.008+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:07.024+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 31: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:07.024+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:11.690+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:12.138+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 32: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:14.260+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:15.722+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:15.792+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 33: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:15.793+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:16.999+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:17.015+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 34: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:17.016+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:18.257+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:18.274+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 35: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:18.275+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:19.518+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:19.551+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 36: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:19.552+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:23.112+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:23.132+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 37: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:23.135+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:24.570+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:24.593+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 38: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:24.593+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:25.875+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:25.896+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 39: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:25.897+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:27.280+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:27.300+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 40: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:27.583+0000] {SaveLinkBatdongsan.py:111} INFO - Saved 60334 links to /opt/***/data/batdongsan_links.txt
[2025-04-14T15:22:27.584+0000] {SaveLinkBatdongsan.py:160} INFO - Progress saved at page 40
[2025-04-14T15:22:27.584+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:30.365+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 41: [Errno 2] No such file or directory: '/home/***/.local/share/undetected_chromedriver/undetected/chromedriver-linux64/chromedriver' -> '/home/***/.local/share/undetected_chromedriver/undetected_chromedriver'
[2025-04-14T15:22:30.380+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:31.840+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:31.867+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 42: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:31.868+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:33.168+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:33.185+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 43: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:33.186+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:34.623+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:34.641+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 44: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:34.642+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:36.176+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:36.201+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 45: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:36.202+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:40.070+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:40.099+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 46: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:40.101+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:41.423+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:41.455+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 47: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:41.456+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:42.726+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:42.761+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 48: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:42.762+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:44.026+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:44.046+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 49: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:44.047+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:45.186+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:45.207+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 50: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:45.463+0000] {SaveLinkBatdongsan.py:111} INFO - Saved 60334 links to /opt/***/data/batdongsan_links.txt
[2025-04-14T15:22:45.463+0000] {SaveLinkBatdongsan.py:160} INFO - Progress saved at page 50
[2025-04-14T15:22:45.463+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:46.617+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:46.642+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 51: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:46.643+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:47.788+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:47.808+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 52: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:47.809+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:48.989+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:49.015+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 53: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:49.016+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:50.576+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:50.639+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 54: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:50.641+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:51.888+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:51.913+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 55: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:51.913+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:53.118+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:53.142+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 56: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:53.143+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:54.522+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:54.549+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 57: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:54.550+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:55.720+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:55.754+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 58: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:55.755+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:57.058+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:57.087+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 59: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:57.087+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:58.308+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:58.332+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 60: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:58.569+0000] {SaveLinkBatdongsan.py:111} INFO - Saved 60334 links to /opt/***/data/batdongsan_links.txt
[2025-04-14T15:22:58.570+0000] {SaveLinkBatdongsan.py:160} INFO - Progress saved at page 60
[2025-04-14T15:22:58.570+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:59.714+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:59.730+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 61: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:59.731+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:00.960+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:00.996+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 62: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:00.997+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:02.579+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:02.599+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 63: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:02.600+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:03.904+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:03.925+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 64: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:03.926+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:05.144+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:05.171+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 65: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:05.172+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:06.583+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 66: [Errno 2] No such file or directory: '/home/***/.local/share/undetected_chromedriver/undetected/chromedriver-linux64/chromedriver' -> '/home/***/.local/share/undetected_chromedriver/undetected_chromedriver'
[2025-04-14T15:23:06.584+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:08.245+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:08.293+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 67: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:08.294+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:09.675+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:09.701+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 68: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:09.701+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:10.937+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:10.956+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 69: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:10.957+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:12.467+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:12.528+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 70: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:12.780+0000] {SaveLinkBatdongsan.py:111} INFO - Saved 60334 links to /opt/***/data/batdongsan_links.txt
[2025-04-14T15:23:12.780+0000] {SaveLinkBatdongsan.py:160} INFO - Progress saved at page 70
[2025-04-14T15:23:12.781+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:13.936+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:13.964+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 71: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:13.965+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:15.438+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:15.465+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 72: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:15.466+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:16.683+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:16.707+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 73: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:16.708+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:17.988+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:18.011+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 74: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:18.011+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:19.316+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:19.338+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 75: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:19.338+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:20.665+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:20.688+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 76: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:20.688+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:22.775+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:22.807+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 77: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:22.808+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:24.569+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:24.594+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 78: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:24.595+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:25.934+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:25.961+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 79: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:25.961+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:27.240+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:27.271+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 80: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:27.629+0000] {SaveLinkBatdongsan.py:111} INFO - Saved 60334 links to /opt/***/data/batdongsan_links.txt
[2025-04-14T15:23:27.630+0000] {SaveLinkBatdongsan.py:160} INFO - Progress saved at page 80
[2025-04-14T15:23:27.630+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:28.741+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:28.759+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 81: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:28.760+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:30.024+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:30.047+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 82: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:30.048+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:31.222+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:31.247+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 83: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:31.248+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:32.413+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:32.436+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 84: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:32.437+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:33.721+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:33.740+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 85: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:33.741+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:34.996+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:35.014+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 86: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:35.015+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:36.406+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:36.433+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 87: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:36.434+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:37.960+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:37.980+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 88: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:37.981+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:39.082+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:39.107+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 89: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:39.108+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:40.213+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:40.236+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 90: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:40.452+0000] {SaveLinkBatdongsan.py:111} INFO - Saved 60334 links to /opt/***/data/batdongsan_links.txt
[2025-04-14T15:23:40.452+0000] {SaveLinkBatdongsan.py:160} INFO - Progress saved at page 90
[2025-04-14T15:23:40.453+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:41.704+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 91: [Errno 2] No such file or directory: '/home/***/.local/share/undetected_chromedriver/undetected/chromedriver-linux64/chromedriver' -> '/home/***/.local/share/undetected_chromedriver/undetected_chromedriver'
[2025-04-14T15:23:41.704+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:43.153+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 92: [Errno 2] No such file or directory: '/home/***/.local/share/undetected_chromedriver/undetected/chromedriver-linux64/chromedriver' -> '/home/***/.local/share/undetected_chromedriver/undetected_chromedriver'
[2025-04-14T15:23:43.154+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:44.775+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:44.813+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 93: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:44.814+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:48.533+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:48.562+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 94: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:48.563+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:52.724+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:52.770+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 95: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:52.772+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:53.951+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:53.968+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 96: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:53.969+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:58.588+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:58.666+0000] {local_task_job_runner.py:318} WARNING - Recorded pid 770 does not match the current pid 215
[2025-04-14T15:23:58.672+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-04-14T15:23:58.840+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 97: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:58.844+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:24:00.773+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:24:00.825+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 98: you cannot reuse the ChromeOptions object
[2025-04-14T15:24:00.826+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:24:02.018+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:24:02.045+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 99: you cannot reuse the ChromeOptions object
[2025-04-14T15:24:02.046+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:24:03.190+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:24:03.208+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 100: you cannot reuse the ChromeOptions object
[2025-04-14T15:24:03.443+0000] {SaveLinkBatdongsan.py:111} INFO - Saved 60334 links to /opt/***/data/batdongsan_links.txt
[2025-04-14T15:24:03.444+0000] {SaveLinkBatdongsan.py:160} INFO - Progress saved at page 100
[2025-04-14T15:24:03.772+0000] {local_task_job_runner.py:318} WARNING - Recorded pid 770 does not match the current pid 215
[2025-04-14T15:24:03.773+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-04-14T15:24:03.785+0000] {SaveLinkBatdongsan.py:111} INFO - Saved 60334 links to /opt/***/data/batdongsan_links.txt
[2025-04-14T15:24:03.788+0000] {SaveLinkBatdongsan.py:170} INFO - Saved 100 error URLs to /opt/***/data/batdongsan_error_links.txt
[2025-04-14T15:24:03.789+0000] {SaveLinkBatdongsan.py:184} INFO - Retrying 100 error URLs...
[2025-04-14T15:24:03.789+0000] {SaveLinkBatdongsan.py:190} INFO - Retrying (1/5): https://batdongsan.com.vn/nha-dat-ban/p1?gtn=7-ty&gcn=30-ty
[2025-04-14T15:24:03.790+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:24:05.231+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:24:05.280+0000] {SaveLinkBatdongsan.py:211} ERROR - Error fetching https://batdongsan.com.vn/nha-dat-ban/p1?gtn=7-ty&gcn=30-ty: you cannot reuse the ChromeOptions object
[2025-04-14T15:24:06.947+0000] {SaveLinkBatdongsan.py:190} INFO - Retrying (2/5): https://batdongsan.com.vn/nha-dat-ban/p1?gtn=7-ty&gcn=30-ty
[2025-04-14T15:24:06.951+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:24:08.606+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:24:08.654+0000] {SaveLinkBatdongsan.py:211} ERROR - Error fetching https://batdongsan.com.vn/nha-dat-ban/p1?gtn=7-ty&gcn=30-ty: you cannot reuse the ChromeOptions object
[2025-04-14T15:24:08.950+0000] {local_task_job_runner.py:318} WARNING - Recorded pid 770 does not match the current pid 215
[2025-04-14T15:24:08.957+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-04-14T15:24:11.128+0000] {SaveLinkBatdongsan.py:190} INFO - Retrying (3/5): https://batdongsan.com.vn/nha-dat-ban/p1?gtn=7-ty&gcn=30-ty
[2025-04-14T15:24:11.144+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:24:12.606+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:24:12.649+0000] {SaveLinkBatdongsan.py:211} ERROR - Error fetching https://batdongsan.com.vn/nha-dat-ban/p1?gtn=7-ty&gcn=30-ty: you cannot reuse the ChromeOptions object
[2025-04-14T15:24:13.959+0000] {SaveLinkBatdongsan.py:190} INFO - Retrying (4/5): https://batdongsan.com.vn/nha-dat-ban/p1?gtn=7-ty&gcn=30-ty
[2025-04-14T15:24:13.965+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:24:15.770+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:24:16.041+0000] {SaveLinkBatdongsan.py:211} ERROR - Error fetching https://batdongsan.com.vn/nha-dat-ban/p1?gtn=7-ty&gcn=30-ty: you cannot reuse the ChromeOptions object
[2025-04-14T15:24:18.962+0000] {SaveLinkBatdongsan.py:190} INFO - Retrying (5/5): https://batdongsan.com.vn/nha-dat-ban/p1?gtn=7-ty&gcn=30-ty
[2025-04-14T15:24:18.963+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:24:19.217+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-04-14T15:24:19.233+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-14T15:24:19.239+0000] {process_utils.py:132} INFO - Sending 15 to group 215. PIDs of all processes in the group: [262, 318, 321, 345, 362, 409, 410, 445, 344, 215]
[2025-04-14T15:24:19.242+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 215
[2025-04-14T15:24:19.251+0000] {taskinstance.py:3094} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-14T15:24:19.280+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=409, status='terminated', started='15:21:20') (409) terminated with exit code None
[2025-04-14T15:24:19.311+0000] {taskinstance.py:3095} ERROR - Stacktrace: 
  File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
  File "/home/***/.local/lib/python3.12/site-packages/***/__main__.py", line 62, in main
    args.func(args)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/scheduler_command.py", line 56, in scheduler
    run_command_with_daemon_option(
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/daemon_utils.py", line 86, in run_command_with_daemon_option
    callback()
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/scheduler_command.py", line 59, in <lambda>
    callback=lambda: _run_scheduler_job(args),
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/scheduler_command.py", line 47, in _run_scheduler_job
    run_job(job=job_runner.job, execute_callable=job_runner._execute)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
  File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
  File "/home/***/.local/lib/python3.12/site-packages/***/jobs/scheduler_job_runner.py", line 990, in _execute
    executor.start()
  File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 392, in start
    self.impl.start()
  File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 330, in start
    worker.start()
  File "/usr/local/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/lib/python3.12/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/lib/python3.12/multiprocessing/context.py", line 282, in _Popen
    return Popen(process_obj)
  File "/usr/local/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/lib/python3.12/multiprocessing/popen_fork.py", line 71, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
  File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 80, in run
    return super().run()
  File "/usr/local/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/traces/tracer.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 211, in do_work
    self.execute_work(key=key, command=command)
  File "/home/***/.local/lib/python3.12/site-packages/***/traces/tracer.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 100, in execute_work
    state = self._execute_work_in_fork(command)
  File "/home/***/.local/lib/python3.12/site-packages/***/traces/tracer.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 142, in _execute_work_in_fork
    args.func(args)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 254, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 322, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
  File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
  File "/home/***/.local/lib/python3.12/site-packages/***/jobs/local_task_job_runner.py", line 171, in _execute
    self.task_runner.start()
  File "/home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py", line 55, in start
    self.process = self._start_by_fork()
  File "/home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/***/.local/lib/python3.12/site-packages/***/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/***/dags/batdongsan_scraping_dag.py", line 40, in save_links_task
    # Use the refactored scraper with custom configuration
  File "/opt/***/dags/../scripts/SaveLinkBatdongsan.py", line 234, in run
    self.logger.info(f"Retry complete. {len(remaining_errors)} failed pages remaining in {self.error_file}.")
  File "/opt/***/dags/../scripts/SaveLinkBatdongsan.py", line 193, in retry_error_urls
  File "/opt/***/dags/../scripts/SaveLinkBatdongsan.py", line 80, in _create_webdriver
    try:
  File "/home/***/.local/lib/python3.12/site-packages/undetected_chromedriver/__init__.py", line 258, in __init__
    self.patcher.auto()
  File "/home/***/.local/lib/python3.12/site-packages/undetected_chromedriver/patcher.py", line 175, in auto
    release = self.fetch_release_number()
  File "/home/***/.local/lib/python3.12/site-packages/undetected_chromedriver/patcher.py", line 250, in fetch_release_number
    with urlopen(self.url_repo + path) as conn:
  File "/usr/local/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.12/urllib/request.py", line 515, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.12/urllib/request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.12/urllib/request.py", line 1392, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/local/lib/python3.12/urllib/request.py", line 1348, in do_open
    r = h.getresponse()
  File "/usr/local/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3095, in signal_handler
    self.log.error("Stacktrace: \n%s", "".join(traceback.format_stack()))

[2025-04-14T15:24:19.332+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=345, status='terminated', started='15:21:20') (345) terminated with exit code None
[2025-04-14T15:24:19.338+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=362, status='terminated', started='15:21:20') (362) terminated with exit code None
[2025-04-14T15:24:19.576+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=445, status='terminated', started='15:21:20') (445) terminated with exit code None
[2025-04-14T15:24:19.793+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=344, status='terminated', started='15:21:20') (344) terminated with exit code None
[2025-04-14T15:24:19.801+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=410, status='terminated', started='15:21:20') (410) terminated with exit code None
[2025-04-14T15:24:19.809+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=318, status='terminated', started='15:21:19') (318) terminated with exit code None
[2025-04-14T15:24:19.812+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=321, status='terminated', started='15:21:19') (321) terminated with exit code None
[2025-04-14T15:24:19.823+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-14T15:24:19.925+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=262, status='terminated', started='15:21:19') (262) terminated with exit code None
[2025-04-14T15:24:19.927+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=215, status='terminated', exitcode=0, started='15:21:17') (215) terminated with exit code 0
