[2025-04-14T15:27:59.072+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-14T15:27:59.154+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: batdongsan_scraping.scrape_data manual__2025-04-14T15:24:27.628506+00:00 [queued]>
[2025-04-14T15:27:59.174+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: batdongsan_scraping.scrape_data manual__2025-04-14T15:24:27.628506+00:00 [queued]>
[2025-04-14T15:27:59.174+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 3
[2025-04-14T15:27:59.223+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): scrape_data> on 2025-04-14 15:24:27.628506+00:00
[2025-04-14T15:27:59.293+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'batdongsan_scraping', 'scrape_data', 'manual__2025-04-14T15:24:27.628506+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/batdongsan_scraping_dag.py', '--cfg-path', '/tmp/tmpquxzkwbq']
[2025-04-14T15:27:59.307+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask scrape_data
[2025-04-14T15:27:59.326+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=8142) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-14T15:27:59.359+0000] {standard_task_runner.py:72} INFO - Started process 8162 to run task
[2025-04-14T15:27:59.607+0000] {task_command.py:467} INFO - Running <TaskInstance: batdongsan_scraping.scrape_data manual__2025-04-14T15:24:27.628506+00:00 [running]> on host 932270897c9d
[2025-04-14T15:27:59.835+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='batdongsan_scraping' AIRFLOW_CTX_TASK_ID='scrape_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-14T15:24:27.628506+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-14T15:24:27.628506+00:00'
[2025-04-14T15:27:59.837+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-14T15:28:00.135+0000] {batdongsan_scraping_dag.py:67} ERROR - Error in scrape_data_task: name 'logging' is not defined
[2025-04-14T15:28:00.136+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/../scripts/ScraperBatdongsan.py", line 231, in scrape_data
    property_data = scrape_property_data(url)
                    ^^^^^^^^^^^^^^^^^^^^
NameError: name 'scrape_property_data' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/dags/../scripts/ScraperBatdongsan.py", line 235, in scrape_data
    logging.error(f"Error scraping {url}: {e}")
    ^^^^^^^
NameError: name 'logging' is not defined. Did you forget to import 'logging'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/batdongsan_scraping_dag.py", line 64, in scrape_data_task
    scrape_data()
  File "/opt/airflow/dags/../scripts/ScraperBatdongsan.py", line 247, in scrape_data
    logging.error(f"Error in scrape_data: {e}")
    ^^^^^^^
NameError: name 'logging' is not defined. Did you forget to import 'logging'
[2025-04-14T15:28:00.276+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=batdongsan_scraping, task_id=scrape_data, run_id=manual__2025-04-14T15:24:27.628506+00:00, execution_date=20250414T152427, start_date=20250414T152759, end_date=20250414T152800
[2025-04-14T15:28:00.402+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-14T15:28:00.407+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 7 for task scrape_data (name 'logging' is not defined; 8162)
Traceback (most recent call last):
  File "/opt/airflow/dags/../scripts/ScraperBatdongsan.py", line 231, in scrape_data
    property_data = scrape_property_data(url)
                    ^^^^^^^^^^^^^^^^^^^^
NameError: name 'scrape_property_data' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/dags/../scripts/ScraperBatdongsan.py", line 235, in scrape_data
    logging.error(f"Error scraping {url}: {e}")
    ^^^^^^^
NameError: name 'logging' is not defined. Did you forget to import 'logging'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/batdongsan_scraping_dag.py", line 64, in scrape_data_task
    scrape_data()
  File "/opt/airflow/dags/../scripts/ScraperBatdongsan.py", line 247, in scrape_data
    logging.error(f"Error in scrape_data: {e}")
    ^^^^^^^
NameError: name 'logging' is not defined. Did you forget to import 'logging'
[2025-04-14T15:28:00.463+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-14T15:28:00.503+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-14T15:28:00.509+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
